name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up latest Go version
        uses: actions/setup-go@v5
        with:
          go-version: "latest"

      - name: Build for Linux, FreeBSD, and OpenBSD
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/goget-linux-amd64
          GOOS=freebsd GOARCH=amd64 go build -o dist/goget-freebsd-amd64
          GOOS=openbsd GOARCH=amd64 go build -o dist/goget-openbsd-amd64

      - name: Generate checksums (.sha256)
        run: |
          cd dist
          sha256sum goget-* > checksums.sha256

      - name: Upload binaries and checksums to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/goget-linux-amd64
            dist/goget-freebsd-amd64
            dist/goget-openbsd-amd64
            dist/checksums.sha256
            LICENSE
